server:
  port: 8989

spring:
  cloud:
    gateway:
      routes:
        - id: auth-management
          uri: lb://AUTH-MANAGEMENT
          predicates:
            - Path=/api/auth/register
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
data:
  redis:
    host: localhost
    port: 6379
    password: root
    timeout: 60000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
jwt:
  secret: mySampleSecureSecretKeyCombinationHere
  expiration: 600000 # 10mins

