spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freedom_banking_transaction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

